import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fetchArchiveKlines } from '../../tools/shared/archiveKlines.js'
import type { Candle } from '../../src/models/price/Candle.js'
import { computeApexBands } from '../../src/core/signals/ApexEngine.js'

type Event = { id:string;symbol:string;timeframe:string;utcAt?:string;direction:'long'|'short'|null;mode:string;signalPresent:boolean;visiblePlan?:{entryApprox?:number;addApprox?:number;stopApprox?:number;fullFixApprox?:number} }
type Data={events:Event[]}
const files=['ci-results/reversal-observed-events-2026-07-30.json','ci-results/reversal-observed-events-2026-07-31.json']
const events=files.flatMap(f=>(JSON.parse(readFileSync(f,'utf8')) as Data).events??[]).filter(e=>e.utcAt&&e.direction&&e.signalPresent)
const CACHE=process.env.CACHE_DIR??'.cache/binance',OUT=process.env.OUT_DIR??'ci-results',FROM=Date.UTC(2026,0,1),UNTIL=Date.UTC(2026,7,1)
const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:NaN
function atr(c:Candle[],i:number,n:number){const a=[] as number[];for(let j=Math.max(0,i-n+1);j<=i;j++){const x=c[j]!;a.push(j===0?x.high-x.low:Math.max(x.high-x.low,Math.abs(x.high-c[j-1]!.close),Math.abs(x.low-c[j-1]!.close)))}return mean(a)}
function realized(c:Candle[],i:number,n:number){const a=[] as number[];for(let j=Math.max(1,i-n+1);j<=i;j++)a.push(Math.log(c[j]!.close/c[j-1]!.close));const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)))}
const groups=new Map<string,Event[]>();for(const e of events){const k=`${e.symbol}|${e.timeframe}`;groups.set(k,[...(groups.get(k)??[]),e])}
const rows=[] as any[]
for(const[k,es]of groups){const[symbol,tf]=k.split('|');if(!['5m','15m','30m','1h','4h'].includes(tf!))continue;const c=await fetchArchiveKlines(symbol!,tf!,'spot',FROM,UNTIL,{cacheDir:CACHE,parallel:10});const bands=computeApexBands(c);for(const e of es){const i=c.findIndex(x=>x.timestamp===Date.parse(e.utcAt!));if(i<200)continue;const x=c[i]!,b=bands[i]!;const plan=e.visiblePlan;const entry=plan?.entryApprox??x.close,add=plan?.addApprox,stop=plan?.stopApprox;const step=add==null?null:Math.abs(entry-add);const stopFromEntry=stop==null?null:Math.abs(entry-stop);const riskFromAvg=add==null||stop==null?null:Math.abs((entry+add)/2-stop);rows.push({id:e.id,symbol,tf,at:e.utcAt,direction:e.direction,mode:e.mode,close:x.close,atr14:atr(c,i,14),atr50:atr(c,i,50),realized20:realized(c,i,20),apexWidthPrice:Number.isFinite(b.mean)?b.mean*b.s:null,entry,add,stop,step,stopFromEntry,riskFromAvg,ratios:{stepAtr14:step==null?null:step/atr(c,i,14),stopEntryAtr14:stopFromEntry==null?null:stopFromEntry/atr(c,i,14),riskAvgAtr14:riskFromAvg==null?null:riskFromAvg/atr(c,i,14),stepApexWidth:step==null||!Number.isFinite(b.mean)?null:step/(b.mean*b.s),stopEntryApexWidth:stopFromEntry==null||!Number.isFinite(b.mean)?null:stopFromEntry/(b.mean*b.s)}})}}
const planRows=rows.filter(r=>r.step!=null)
const md=`# Reversal volatility geometry v0.1\n\n- Author statement: stop is not very short and adapts to current volatility so market noise does not knock it out; position risk must then be sized correctly to avoid liquidation.\n- This statement is about **trade geometry and position sizing**, not necessarily the BUY/SELL trigger.\n- Feed: Binance Spot OHLCV; visible plan levels are only used where a screenshot/OCR observation exists.\n- Production defaults changed: **NO**.\n\n| ID | Mode | TF | Step | Stop from entry | Step/ATR14 | Stop/ATR14 | Step/Apex width | Stop/Apex width |\n|---|---|---:|---:|---:|---:|---:|---:|---:|\n${planRows.map(r=>`| ${r.id} | ${r.mode} | ${r.tf} | ${r.step.toFixed(4)} | ${r.stopFromEntry.toFixed(4)} | ${r.ratios.stepAtr14.toFixed(3)} | ${r.ratios.stopEntryAtr14.toFixed(3)} | ${r.ratios.stepApexWidth?.toFixed(3)??'—'} | ${r.ratios.stopEntryApexWidth?.toFixed(3)??'—'} |`).join('\n')}\n\n## Interpretation\n\n1. First test the already observed mirror identity stop ≈ 2×add − entry; this fixes geometry before guessing volatility.\n2. Then compare the step with ATR14/ATR50, realized volatility and Apex width across modes/assets/TF.\n3. If one normalized ratio is stable cross-symbol and cross-TF, it likely controls Safe/Risk step length.\n4. Position size is a separate calculation: fixed account risk divided by stop distance. A volatility-adaptive wider stop must reduce position size; leverage does not repair risk.\n\nThe current screenshot set contains too few exact plan levels for a statistically reliable cross-asset ratio. Additional plan screenshots should show entry/add/stop and exact signal bar together.\n`
mkdirSync(OUT,{recursive:true});writeFileSync(`${OUT}/reversal-volatility-geometry-v0.1.json`,JSON.stringify({meta:{from:FROM,until:UNTIL,market:'spot'},rows},null,2));writeFileSync(`${OUT}/reversal-volatility-geometry-v0.1.md`,md);console.log(md)
