import {execFileSync} from'node:child_process';import{existsSync,mkdirSync,writeFileSync}from'node:fs';
const C=process.env.CACHE_DIR??'.cache/binance',O=process.env.OUT_DIR??'ci-results';type B={t:number,h:number,l:number,c:number};
const X=[{id:'BTC 15m',s:'BTCUSDT',tf:'15m',t:Date.UTC(2026,6,27,14,30),m:65150.76,u:65836.23,d:64472.44},{id:'ETH 1h',s:'ETHUSDT',tf:'1h',t:Date.UTC(2026,6,28,3),m:1899.35,u:1955.86,d:1844.46}];
const months=['2025-09','2025-10','2025-11','2025-12','2026-01','2026-02','2026-03','2026-04','2026-05','2026-06'],days=Array.from({length:28},(_,i)=>`2026-07-${String(i+1).padStart(2,'0')}`),base='https://data.binance.vision/data/spot';
async function get(u:string){const f=`${C}/${u.split('/').pop()}`;if(existsSync(f))return f;const r=await fetch(u);if(!r.ok)return null;writeFileSync(f,Buffer.from(await r.arrayBuffer()));return f}function uz(f:string){const a:B[]=[];for(const z of execFileSync('unzip',['-p',f],{maxBuffer:1<<28}).toString().split('\n')){const p=z.split(',');let t=+p[0]!;if(!Number.isFinite(t)||p.length<5)continue;if(t>1e14)t=Math.floor(t/1000);a.push({t,h:+p[2]!,l:+p[3]!,c:+p[4]!})}return a}
async function load(s:string,tf:string){const a:B[]=[];for(const q of [...months.map(x=>`monthly/klines/${s}/${tf}/${s}-${tf}-${x}.zip`),...days.map(x=>`daily/klines/${s}/${tf}/${s}-${tf}-${x}.zip`)]){const f=await get(`${base}/${q}`);if(f)a.push(...uz(f))}const m=new Map(a.map(x=>[x.t,x]));return[...m.values()].sort((x,y)=>x.t-y.t)}
function w(n:number,o:number,g:number){const a=new Float64Array(n),m=o*(n-1),s=n/g;let d=0;for(let j=0;j<n;j++){a[j]=Math.exp(-((j-m)**2)/(2*s*s));d+=a[j]!}for(let j=0;j<n;j++)a[j]=a[j]!/d;return a}function dot(a:number[],i:number,q:Float64Array){let z=0;for(let j=0;j<q.length;j++)z+=q[j]!*a[i-q.length+1+j]!;return z}const pc=(a:number,b:number)=>(a/b-1)*100,F=(a:number)=>a.toFixed(3),mw=w(200,.85,6);
const P=[{name:'v6 accepted',n:122,o:.675,g:3.5,norm:'mean'},{name:'v6 best-shape',n:122,o:.625,g:3.5,norm:'own'},{name:'near-200',n:204,o:.8,g:6.5,norm:'mean'},{name:'vendor-shape',n:200,o:.85,g:6,norm:'mean'}];
async function main(){mkdirSync(C,{recursive:true});mkdirSync(O,{recursive:true});let md=`# Apex cross-check: BTC 15m + ETH 1h\n\n- прогон ${process.env.GITHUB_RUN_ID??'local'}\n- эти точки не участвовали в подборе\n\n|точка|target s|ошибка mean ALMA200 %|`+P.map(x=>`${x.name} %`).join('|')+'|\n|---|---:|---:|'+P.map(()=>'---:').join('|')+'|\n';for(const x of X){const a=await load(x.s,x.tf),i=a.findIndex(b=>b.t===x.t);if(i<0)throw Error(`нет ${x.id}`);const src=a.map(b=>(b.h+b.l+b.c)/3),mean=dot(src,i,mw),tr=a.map((b,j)=>j?Math.max(b.h-b.l,Math.abs(b.h-a[j-1]!.c),Math.abs(b.l-a[j-1]!.c)):b.h-b.l),target=(Math.log(x.u/x.m)+Math.log(x.m/x.d))/(11.2),e=[];for(const p of P){const q=w(p.n,p.o,p.g);let v;if(p.norm==='own')v=dot(tr.map((z,j)=>z/a[j]!.c),i,q);else v=dot(tr,i,q)/mean;e.push(pc(v,target))}md+=`|${x.id}|${target.toFixed(6)}|${F(pc(mean,x.m))}|${e.map(F).join('|')}|\n`}md+='\nПорог внешней проверки: абсолютная ошибка каждой новой точки <=3%.\n';writeFileSync(`${O}/apex-cross-check.md`,md)}await main();
