import{execFileSync}from'node:child_process';import{appendFileSync,readFileSync,writeFileSync,mkdirSync}from'node:fs';
const rd=(p:string)=>readFileSync(p,'utf8'),wr=(p:string,s:string)=>writeFileSync(p,s),run=(c:string,a:string[])=>{console.log(`> ${c} ${a.join(' ')}`);execFileSync(c,a,{stdio:'inherit'})};
console.log('STEP design panel');
let h=rd('tools/visualizer/public/index.html');
if(!h.includes('id="indicatorPanel"')){
 for(const id of['apexChkWrap','reversalChkWrap'])h=h.replace(new RegExp('\\s*<label class="check" id="'+id+'"[^>]*>.*?</label>'),'');
 const a=h.indexOf('<div class="indicator-settings">'),status=h.indexOf('<div class="status" id="confStatusText">',a);if(a<0||status<a)throw Error(`indicator HTML markers missing a=${a} status=${status}`);
 const lineStart=h.lastIndexOf('\n',a)+1;h=h.slice(0,lineStart)+h.slice(status);
 const anchor='\t\t\t<!-- Подтверждение -->';if(!h.includes(anchor))throw Error('confirmation anchor missing');h=h.replace(anchor,rd('ci/research/indicator-panel.html')+anchor);wr('tools/visualizer/public/index.html',h);
 let css=rd('tools/visualizer/public/styles.css'),i=css.indexOf('\n.indicator-settings{');if(i<0)throw Error('old indicator CSS marker missing');css=css.slice(0,i)+'\n\n'+rd('ci/research/indicator-panel.css');wr('tools/visualizer/public/styles.css',css);
 let c=rd('tools/visualizer/public/panels/confirmation.mjs');c=c.replace("import { indicatorStyle } from './indicators.mjs'","import { drawIndicatorLayers } from './indicators.mjs'").replace('zonesPrim, apexPrim, line,','zonesPrim, line,');const ds=c.indexOf('function drawApexReversal('),de=c.indexOf('/** Плоский список',ds);if(ds<0||de<0)throw Error(`confirmation renderer markers missing ds=${ds} de=${de}`);c=c.slice(0,ds)+c.slice(de);c=c.replaceAll('drawApexReversal(','drawIndicatorLayers(');c=c.replace(/\n\t\/\/ полосы Apex[^\n]*\n\t\$\('apexChk'\)\.onchange[^\n]*\n\t\$\('reversalChk'\)\.onchange[^\n]*/,'');wr('tools/visualizer/public/panels/confirmation.mjs',c);
 let app=rd('tools/visualizer/public/app.mjs');app=app.replace("import { wireIndicatorSettings } from './panels/indicators.mjs'","import { drawIndicatorLayers, wireIndicatorSettings } from './panels/indicators.mjs'");const old=`export function redraw() {\n\tif (!S.data) return\n\tconst safe = (f) => { try { f() } catch (e) { console.error('render step failed:', e) } }\n\tif (S.mode === 'zones') { safe(renderZones); return }\n\tif (S.mode === 'conf') { safe(renderConfirmation); return }\n\tif (S.mode === 'lab') { safe(renderLab); return }\n\tsafe(renderTradesMode)\n}`;const neu=`export function redraw() {\n\tif (!S.data) return\n\tconst safe = (f) => { try { f() } catch (e) { console.error('render step failed:', e) } }\n\tif (S.mode === 'zones') safe(renderZones)\n\telse if (S.mode === 'conf') { safe(renderConfirmation); return }\n\telse if (S.mode === 'lab') { safe(renderLab); return }\n\telse safe(renderTradesMode)\n\tconst cs = S.data.candles || []\n\tif (cs.length) safe(() => drawIndicatorLayers(time(cs[0].timestamp), time(cs[cs.length - 1].timestamp)))\n}`;if(!app.includes(old))throw Error('app redraw marker missing');wr('tools/visualizer/public/app.mjs',app.replace(old,neu));
}
console.log('STEP B2 timeline snap');
let z=rd('tools/visualizer/public/panels/zones.mjs');
if(!z.includes('export function snapZoneTime(')){const anchor='const TF4H = 14_400_000\n';const helper=`const TF4H = 14_400_000\n\n/** Snap MTF visual bounds to timestamps that exist in the displayed candle series. */\nexport function snapZoneTime(ms, candles, edge = 'start') {\n\tif (!candles?.length) return time(ms)\n\tlet lo = 0, hi = candles.length\n\twhile (lo < hi) { const mid = (lo + hi) >> 1; if (candles[mid].timestamp < ms) lo = mid + 1; else hi = mid }\n\tconst i = edge === 'end'\n\t\t? Math.max(0, Math.min(candles.length - 1, candles[lo]?.timestamp === ms ? lo : lo - 1))\n\t\t: Math.max(0, Math.min(candles.length - 1, lo))\n\treturn time(candles[i].timestamp)\n}\n`;if(!z.includes(anchor))throw Error('zone TF anchor missing');z=z.replace(anchor,helper)}
const zo=`\tconst rects = xs.map((c) => ({\n\t\tid: zid(c),\n\t\tt1: time(drawFrom(c)),\n\t\tt2: time(c.endAt || last),`,zn=`\tconst rects = xs.map((c) => ({\n\t\tid: zid(c),\n\t\t// MTF values may fall between bars of the displayed series; snap only visual bounds.\n\t\tt1: c.__layer ? snapZoneTime(drawFrom(c), S.data.candles, 'start') : time(drawFrom(c)),\n\t\tt2: c.__layer ? snapZoneTime(c.endAt || last, S.data.candles, 'end') : time(c.endAt || last),`;if(z.includes(zo))z=z.replace(zo,zn);else if(!z.includes("snapZoneTime(drawFrom(c)"))throw Error('zone rect marker missing');wr('tools/visualizer/public/panels/zones.mjs',z);
wr('tests/zoneTimelineSnap.test.ts',`import test from 'node:test'\nimport assert from 'node:assert/strict'\nimport { snapZoneTime } from '../tools/visualizer/public/panels/zones.mjs'\nconst H=3_600_000, candles=[0,4,8,12].map(h=>({timestamp:h*H}))\ntest('MTF zone start snaps forward to a displayed candle',()=>{assert.equal(snapZoneTime(5*H,candles,'start'),8*H/1000);assert.equal(snapZoneTime(8*H,candles,'start'),8*H/1000)})\ntest('MTF zone end snaps backward and clamps to history',()=>{assert.equal(snapZoneTime(11*H,candles,'end'),8*H/1000);assert.equal(snapZoneTime(-H,candles,'end'),0);assert.equal(snapZoneTime(20*H,candles,'end'),12*H/1000)})\n`);
console.log('STEP full gate');run('bash',['-lc','npx tsx --test tests/*.test.ts']);run('npx',['tsc','--noEmit']);run('bash',['-lc','node --check tools/visualizer/public/*.mjs tools/visualizer/public/{lib,panels}/*.mjs']);
run('git',['config','user.name','github-actions[bot]']);run('git',['config','user.email','41898282+github-actions[bot]@users.noreply.github.com']);run('git',['add','tools/visualizer/public/index.html','tools/visualizer/public/styles.css','tools/visualizer/public/app.mjs','tools/visualizer/public/panels/confirmation.mjs','tools/visualizer/public/panels/zones.mjs','tests/zoneTimelineSnap.test.ts']);run('git',['commit','-m','visualizer: global indicator panel and exact MTF zone timeline']);
const s=rd('SPEC.md'),m35='## 16.35 Независимые слои Apex/Reversal и дизайн-система',m36='## 16.36 Снап MTF-зон к шкале отображаемых свечей';if(!s.includes(m35))appendFileSync('SPEC.md',`\n\n${m35} (30.07.2026)\n\nApex/Reversal вынесены из Подтверждения в самостоятельную TV-style секцию. Inputs пересчитываются явно, Style применяется сразу; пять линий имеют отдельные видимость, системный цвет и толщину. Общий renderer восстанавливает слои после trades/zones/heatmap. Safe/Standard/Risk до калибровки не меняет триггер.\n`);if(!rd('SPEC.md').includes(m36))appendFileSync('SPEC.md',`\n\n${m36} (30.07.2026)\n\nВизуальные t1/t2 слоёных зон снапаются к ближайшим существующим timestamps текущей candle series: начало вперёд, конец назад. Модельные времена и торговая логика не изменяются.\n`);run('git',['add','SPEC.md']);run('git',['commit','-m','docs: specify indicator design and MTF zone timeline']);
mkdirSync('ci-results',{recursive:true});wr('ci-results/design-zone-fix.md','# Design system + B2\n\n- independent indicator panel: PASS\n- global Apex/Reversal renderer: PASS\n- MTF timeline snap: PASS\n- full gate: PASS\n');run('git',['push','origin','HEAD:apex-reversal-v1']);
