import{execFileSync}from'node:child_process';import{appendFileSync,readFileSync,writeFileSync}from'node:fs';
const run=(c:string,a:string[],o:any={})=>execFileSync(c,a,{stdio:'inherit',...o}),rd=(p:string)=>readFileSync(p,'utf8'),wr=(p:string,s:string)=>writeFileSync(p,s);
run('git',['pull','--rebase','origin','apex-reversal-v1']);
let z=rd('tools/visualizer/public/panels/zones.mjs');const anchor=`const TF4H = 14_400_000\n`;const helper=`const TF4H = 14_400_000\n\n/**\n * Слоёная зона может родиться внутри свечи отображаемого HTF. Lightweight Charts\n * возвращает null для времени, которого нет в series; renderer раньше заменял null\n * координатой 0 и приклеивал прямоугольник к левому краю. Снап выполняется только\n * для визуальной геометрии: модельные knownAt/endAt и порядок зон не меняются.\n */\nexport function snapZoneTime(ms, candles, edge = 'start') {\n\tif (!candles?.length) return time(ms)\n\tlet lo = 0, hi = candles.length\n\twhile (lo < hi) {\n\t\tconst mid = (lo + hi) >> 1\n\t\tif (candles[mid].timestamp < ms) lo = mid + 1\n\t\telse hi = mid\n\t}\n\tconst i = edge === 'end'\n\t\t? Math.max(0, Math.min(candles.length - 1, candles[lo]?.timestamp === ms ? lo : lo - 1))\n\t\t: Math.max(0, Math.min(candles.length - 1, lo))\n\treturn time(candles[i].timestamp)\n}\n`;if(!z.includes(anchor))throw Error('TF anchor missing');z=z.replace(anchor,helper);
const old=`\tconst rects = xs.map((c) => ({\n\t\tid: zid(c),\n\t\tt1: time(drawFrom(c)),\n\t\tt2: time(c.endAt || last),`;const neu=`\tconst rects = xs.map((c) => ({\n\t\tid: zid(c),\n\t\t// MTF timestamps (например 1h на 4h-графике) снапаем к реальным барам\n\t\t// текущей series: timeToCoordinate больше не получает отсутствующее время.\n\t\tt1: c.__layer ? snapZoneTime(drawFrom(c), S.data.candles, 'start') : time(drawFrom(c)),\n\t\tt2: c.__layer ? snapZoneTime(c.endAt || last, S.data.candles, 'end') : time(c.endAt || last),`;if(!z.includes(old))throw Error('rect timeline block missing');z=z.replace(old,neu);wr('tools/visualizer/public/panels/zones.mjs',z);
wr('tests/zoneTimelineSnap.test.ts',`import test from 'node:test'\nimport assert from 'node:assert/strict'\nimport { snapZoneTime } from '../tools/visualizer/public/panels/zones.mjs'\n\nconst H=3_600_000\nconst candles=[0,4,8,12].map(h=>({timestamp:h*H}))\ntest('layer-zone start snaps forward to an existing displayed candle',()=>{\n assert.equal(snapZoneTime(5*H,candles,'start'),8*H/1000)\n assert.equal(snapZoneTime(8*H,candles,'start'),8*H/1000)\n})\ntest('layer-zone end snaps backward and clamps to available history',()=>{\n assert.equal(snapZoneTime(11*H,candles,'end'),8*H/1000)\n assert.equal(snapZoneTime(-H,candles,'end'),0)\n assert.equal(snapZoneTime(20*H,candles,'end'),12*H/1000)\n})\n`);
run('bash',['-lc','npx tsx --test tests/*.test.ts']);run('npx',['tsc','--noEmit']);run('bash',['-lc','node --check tools/visualizer/public/*.mjs tools/visualizer/public/{lib,panels}/*.mjs']);
run('git',['config','user.name','github-actions[bot]']);run('git',['config','user.email','41898282+github-actions[bot]@users.noreply.github.com']);run('git',['add','tools/visualizer/public/panels/zones.mjs','tests/zoneTimelineSnap.test.ts']);run('git',['commit','-m','visualizer: snap layered zones to displayed candle timeline']);
const mark='## 16.36 Снап MTF-зон к шкале отображаемых свечей';if(!rd('SPEC.md').includes(mark))appendFileSync('SPEC.md',`\n\n${mark} (29.07.2026)\n\nВизуальные t1/t2 слоёных зон снапаются к ближайшим реально существующим timestamps текущей candle series: начало вперёд, конец назад. Это устраняет null из timeToCoordinate и ложную координату x=0 для 1h-зон на 4h/1D-графике. Модельные времена knownAt/endAt, отбор nearestLocal и торговая логика не изменяются.\n`);run('git',['add','SPEC.md']);run('git',['commit','-m','docs: specify layered-zone timeline snapping']);run('git',['push','origin','HEAD:apex-reversal-v1']);
