import{execFileSync}from'node:child_process';import{writeFileSync,mkdirSync}from'node:fs';
import type{Candle}from'../../src/models/price/Candle.js';import{computeApexBands}from'../../src/core/signals/ApexEngine.js';import{fetchArchiveKlines}from'../../tools/shared/archiveKlines.js';
const OUT=process.env.OUT_DIR??'ci-results',CACHE=process.env.CACHE_DIR??'.cache/binance';mkdirSync(OUT,{recursive:true});
execFileSync('bash',['-lc','npx tsx --test tests/*.test.ts && npx tsc --noEmit'],{stdio:'inherit'});
const FROM=Date.UTC(2023,0,1),SPLIT=Date.UTC(2025,0,1),UNTIL=Date.UTC(2026,6,30),COST=.001,H=[4,12,24]as const;
const symbols=['BTC/USDT','ETH/USDT','SOL/USDT','XRP/USDT'],tfs=['5m','15m','1h'];
type Edge='inner'|'outer';type Confirm='touch'|'directional'|'reclaim-edge'|'reclaim-inner';type Rearm='mean'|'inner';type Cfg={edge:Edge;confirm:Confirm;rearm:Rearm;id:string};
const cfgs:Cfg[]=[];for(const edge of['inner','outer']as Edge[])for(const confirm of['touch','directional','reclaim-edge','reclaim-inner']as Confirm[]){if(edge==='inner'&&confirm==='reclaim-inner')continue;for(const rearm of['mean','inner']as Rearm[])cfgs.push({edge,confirm,rearm,id:`${edge}/${confirm}/${rearm}`})}
type Sig={i:number;at:number;dir:'long'|'short'};
function signals(c:Candle[],cfg:Cfg):Sig[]{const b=computeApexBands(c),out:Sig[]=[];let al=true,as=true,pl=false,ps=false;for(let i=0;i<c.length;i++){const x=c[i]!,z=b[i]!;if(!Number.isFinite(z.mean))continue;const le=cfg.edge==='outer'?z.greenLo:z.greenHi,se=cfg.edge==='outer'?z.redHi:z.redLo;const lr=cfg.rearm==='mean'?z.mean:z.greenHi,sr=cfg.rearm==='mean'?z.mean:z.redLo;if(!al&&x.close>=lr){al=true;pl=false}if(!as&&x.close<=sr){as=true;ps=false}const tl=al&&x.low<=le,ts=as&&x.high>=se;if(tl)pl=true;if(ts)ps=true;const bullish=x.close>x.open,bearish=x.close<x.open;let okL=false,okS=false;if(cfg.confirm==='touch'){okL=tl;okS=ts}else if(cfg.confirm==='directional'){okL=pl&&bullish;okS=ps&&bearish}else if(cfg.confirm==='reclaim-edge'){okL=pl&&bullish&&x.close>=le;okS=ps&&bearish&&x.close<=se}else{okL=pl&&bullish&&x.close>=z.greenHi;okS=ps&&bearish&&x.close<=z.redLo}if(okL&&okS){if(bullish)okS=false;else if(bearish)okL=false;else{const lp=(le-x.low)/x.close,sp=(x.high-se)/x.close;if(lp>=sp)okS=false;else okL=false}}if(okL){out.push({i,at:x.timestamp,dir:'long'});al=false;pl=false}else if(okS){out.push({i,at:x.timestamp,dir:'short'});as=false;ps=false}if(x.close>=z.mean)pl=false;if(x.close<=z.mean)ps=false}return out}
type Obs={cfg:string,symbol:string,tf:string,split:'train'|'test',h:number,dir:'long'|'short',ret:number,mfe:number,mae:number};const obs:Obs[]=[];const coverage:any[]=[];
for(const symbol of symbols)for(const tf of tfs){console.log('load',symbol,tf);const c=await fetchArchiveKlines(symbol,tf,'futures',FROM,UNTIL,{cacheDir:CACHE,parallel:6});coverage.push({symbol,tf,bars:c.length,from:c[0]?.timestamp??null,to:c.at(-1)?.timestamp??null});console.log('bars',c.length);for(const cfg of cfgs)for(const s of signals(c,cfg)){for(const h of H){if(s.i+h>=c.length)continue;const e=c[s.i]!.close,dir=s.dir==='long'?1:-1,end=c[s.i+h]!.close;let mfe=-Infinity,mae=Infinity;for(let j=s.i+1;j<=s.i+h;j++){const x=c[j]!;const fav=s.dir==='long'?x.high/e-1:1-x.low/e;const adv=s.dir==='long'?x.low/e-1:1-x.high/e;mfe=Math.max(mfe,fav);mae=Math.min(mae,adv)}obs.push({cfg:cfg.id,symbol,tf,split:s.at<SPLIT?'train':'test',h,dir:s.dir,ret:dir*(end/e-1),mfe,mae})}}}
const avg=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:NaN,sd=(x:number[])=>{const m=avg(x);return Math.sqrt(avg(x.map(v=>(v-m)**2)))},pct=(x:number)=>Number.isFinite(x)?(100*x).toFixed(3)+'%':'—';
type Row={cfg:string,split:string,h:number,n:number,longPct:number,meanGross:number,meanNet:number,medianNet:number,winNet:number,mfe:number,mae:number,t:number};
const rows:Row[]=[];for(const cfg of cfgs)for(const split of['train','test']as const)for(const h of H){const x=obs.filter(o=>o.cfg===cfg.id&&o.split===split&&o.h===h),nets=x.map(o=>o.ret-COST).sort((a,b)=>a-b),m=avg(nets),se=sd(nets)/Math.sqrt(nets.length);rows.push({cfg:cfg.id,split,h,n:x.length,longPct:x.length?x.filter(o=>o.dir==='long').length/x.length:NaN,meanGross:avg(x.map(o=>o.ret)),meanNet:m,medianNet:nets.length?nets[Math.floor(nets.length/2)]!:NaN,winNet:nets.length?nets.filter(v=>v>0).length/nets.length:NaN,mfe:avg(x.map(o=>o.mfe)),mae:avg(x.map(o=>o.mae)),t:se>0?m/se:NaN})}
const r=(cfg:string,split:string,h=12)=>rows.find(x=>x.cfg===cfg&&x.split===split&&x.h===h)!;const ranked=cfgs.map(c=>({cfg:c.id,train:r(c.id,'train'),test:r(c.id,'test')})).filter(x=>x.train.n>=500).sort((a,b)=>b.train.meanNet-a.train.meanNet);const baseline='outer/directional/mean';
const line=(x:Row)=>`n=${x.n}, net=${pct(x.meanNet)}, med=${pct(x.medianNet)}, win=${pct(x.winNet)}, MFE=${pct(x.mfe)}, MAE=${pct(x.mae)}, t=${Number.isFinite(x.t)?x.t.toFixed(2):'—'}`;let md=`# Zonda Reversal — trigger-family baseline\n\n- Data: Binance Futures archives, ${symbols.join(', ')}, TF ${tfs.join(', ')}\n- Range: 2023-01-01..2026-07-29; split: 2025-01-01\n- Entry convention: signal on closed bar, entry at its close; touch is an OHLC intrabar-proxy evaluated at close\n- Round-trip cost: ${(COST*100).toFixed(2)}% of price\n- Production defaults changed: **NO**\n\n## Coverage\n\n| Symbol | TF | Bars | From | To |\n|---|---:|---:|---|---|\n${coverage.map(x=>`| ${x.symbol} | ${x.tf} | ${x.bars} | ${x.from?new Date(x.from).toISOString().slice(0,10):'—'} | ${x.to?new Date(x.to).toISOString().slice(0,10):'—'} |`).join('\n')}\n\n## Current baseline (${baseline}, horizon 12)\n\n- train: ${line(r(baseline,'train'))}\n- test: ${line(r(baseline,'test'))}\n\n## Ranked only by train mean net return, horizon 12\n\n| # | Hypothesis | Train | Untouched test |\n|---:|---|---|---|\n${ranked.map((x,i)=>`| ${i+1} | ${x.cfg} | ${line(x.train)} | ${line(x.test)} |`).join('\n')}\n\n## Top-5 train candidates across horizons\n\n${ranked.slice(0,5).map(x=>`### ${x.cfg}\n${H.map(h=>`- ${h} bars — train: ${line(r(x.cfg,'train',h))}; test: ${line(r(x.cfg,'test',h))}`).join('\n')}`).join('\n\n')}\n\n## Interpretation rules\n\n- Names above are research hypotheses, **not** claimed mappings to vendor Safe/Standard/Risk.\n- A candidate is actionable only if sign and useful magnitude survive untouched test, long/short and TF slices.\n- Multiple horizons share signals; t-stat is descriptive, not a final significance claim.\n- Next step: robustness slices and mode mapping only after this baseline.\n`;
writeFileSync(`${OUT}/reversal-baseline.md`,md);writeFileSync(`${OUT}/reversal-baseline.json`,JSON.stringify({meta:{from:FROM,split:SPLIT,until:UNTIL,cost:COST,symbols,tfs,horizons:H},coverage,cfgs,rows,ranked},null,2));console.log(md);
