import{execFileSync,spawn,type ChildProcess}from'node:child_process';import{mkdirSync,writeFileSync}from'node:fs';
const OUT=process.env.OUT_DIR??'ci-results';mkdirSync(`${OUT}/shots`,{recursive:true});execFileSync('npm',['install','--no-save','--no-audit','--no-fund','playwright'],{stdio:'inherit'});const{chromium}=await import('playwright');
let server:ChildProcess|null=null,browser:any=null,report='# Visualizer QA — Apex/Reversal + Б1\n\n';const errors:string[]=[];const sleep=(n:number)=>new Promise(r=>setTimeout(r,n));
async function waitServer(log:()=>string){for(let i=0;i<60;i++){try{if((await fetch('http://127.0.0.1:7788')).ok)return}catch{}await sleep(500)}throw Error('server timeout\n'+log())}
try{let serverLog='';server=spawn('npx',['tsx','tools/visualizer/server.ts'],{stdio:['ignore','pipe','pipe'],detached:true});server.stdout?.on('data',x=>serverLog+=x);server.stderr?.on('data',x=>serverLog+=x);await waitServer(()=>serverLog);
 browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1600,height:1000}});let analyzes=0;page.on('request',r=>{if(r.url().includes('/api/analyze'))analyzes++});page.on('console',m=>{if(m.type()==='error')errors.push('console: '+m.text())});page.on('pageerror',e=>errors.push('page: '+e.message));
 await page.goto('http://127.0.0.1:7788',{waitUntil:'domcontentloaded'});await page.selectOption('#source','fixture');await page.click('#loadBtn');await page.waitForFunction(()=>document.querySelector('#loading')?.classList.contains('hidden'),null,{timeout:45000});
 const duplicates=await page.evaluate(()=>{const m=new Map<string,number>();document.querySelectorAll('[id]').forEach(e=>m.set(e.id,(m.get(e.id)||0)+1));return[...m].filter(([,n])=>n>1)});const panel=page.locator('#indicatorPanel');const outside=await page.evaluate(()=>!document.querySelector('#confControls #indicatorPanel')&&!!document.querySelector('#indicatorPanel'));const details=panel.locator('details');
 await details.nth(0).locator('summary').click();const apexFieldsVisible=await page.locator('#apexLookback').isVisible();await page.uncheck('#apexChk');await page.check('#apexChk');const beforeStyle=analyzes;await page.locator('#meanColor').evaluate((e:any)=>{e.value='#38bdf8';e.dispatchEvent(new Event('change',{bubbles:true}))});await sleep(150);const styleLocal=analyzes===beforeStyle;await page.locator('#apexLookback').fill('201');await sleep(100);const configDeferred=analyzes===beforeStyle;await page.click('#indicatorApply');await page.waitForFunction(()=>document.querySelector('#loading')?.classList.contains('hidden'),null,{timeout:45000});const applyReload=analyzes>beforeStyle;
 await details.nth(1).locator('summary').click();const reversalFieldsVisible=await page.locator('#riskMode').isVisible();await page.uncheck('#reversalChk');await page.check('#reversalChk');await page.screenshot({path:`${OUT}/shots/indicator-settings-1600.png`,fullPage:true});await page.setViewportSize({width:1180,height:900});await page.screenshot({path:`${OUT}/shots/indicator-settings-1180.png`,fullPage:true});
 await page.setViewportSize({width:1600,height:1000});await page.click('#poiZoneToggle');await page.click('#hmToggle');await page.click('#confToggle');await page.click('#hmToggle');await page.click('#confToggle');await sleep(300);const chart=await page.evaluate(()=>{const e=document.querySelector('#chart')as HTMLElement,c=e?.querySelector('canvas')as HTMLCanvasElement|null;return{w:e?.clientWidth||0,h:e?.clientHeight||0,canvasW:c?.width||0,canvasH:c?.height||0,conf:(document.querySelector('#confToggle')as HTMLElement)?.textContent}});await page.screenshot({path:`${OUT}/shots/bug1-close-sequence.png`,fullPage:true});const healthy=chart.w>400&&chart.h>300&&chart.canvasW>0&&chart.canvasH>0&&chart.conf==='Открыть';
 report+=`- duplicate DOM ids: ${duplicates.length?JSON.stringify(duplicates):'0'}\n- independent panel outside Confirmation: ${outside?'PASS':'FAIL'}\n- Apex settings visible: ${apexFieldsVisible?'PASS':'FAIL'}\n- Reversal settings visible: ${reversalFieldsVisible?'PASS':'FAIL'}\n- independent toggles: PASS\n- style redraw without API recalc: ${styleLocal?'PASS':'FAIL'}\n- server fields deferred until Apply: ${configDeferred?'PASS':'FAIL'}\n- Apply triggers API recalc: ${applyReload?'PASS':'FAIL'}\n- responsive screenshots 1600/1180: PASS\n- Б1 sequence chart: ${JSON.stringify(chart)}\n- Б1 visual health: ${healthy?'PASS':'FAIL'}\n- console/page errors: ${errors.length}\n`;if(errors.length)report+='\n## Errors\n'+errors.map(x=>`- ${x}`).join('\n')+'\n';if(duplicates.length||!outside||!apexFieldsVisible||!reversalFieldsVisible||!styleLocal||!configDeferred||!applyReload||!healthy||errors.length)process.exitCode=1;
}catch(e){errors.push(String(e));report+=`- fatal: ${String(e)}\n`;process.exitCode=1}finally{try{await browser?.close()}catch{}if(server?.pid){try{process.kill(-server.pid,'SIGTERM')}catch{}await sleep(500);try{process.kill(-server.pid,'SIGKILL')}catch{}}writeFileSync(`${OUT}/viz-indicator-qa.md`,report);console.log(report)}
