// Historical USD-M futures metrics from data.binance.vision.
// Binance publishes this dataset as DAILY files only (monthly path is absent).
import{existsSync,mkdirSync,readFileSync,writeFileSync}from'node:fs';import{join}from'node:path';
import type{Candle}from'../../src/models/price/Candle.js';import{archiveSymbol,unzipCsv}from'./archiveKlines.js';
const BASE='https://data.binance.vision/data/futures/um/daily/metrics',DAY=86_400_000;export const ARCHIVE_METRICS_INTERVAL_MS=300_000;
export interface ArchiveMetricPoint{timestamp:number;oi:number;oiValue:number|null;takerBuyRatio:number|null}
export interface ArchiveMetricOptions{fetchImpl?:typeof fetch;cacheDir?:string;parallel?:number}
const ts=(raw:string):number=>{if(/^\d+$/.test(raw)){let n=Number(raw);if(n>1e14)n=Math.round(n/1000);else if(n<1e12)n*=1000;return n}const z=raw.trim().replace(' ','T');return Date.parse(/[zZ]|[+-]\d\d:?\d\d$/.test(z)?z:`${z}Z`)};
export function parseMetricsCsv(text:string):ArchiveMetricPoint[]{const lines=text.split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const head=lines[0]!.split(',').map(x=>x.trim().toLowerCase());const col=(...names:string[])=>names.map(n=>head.indexOf(n)).find(i=>i>=0)??-1;const ti=col('create_time','timestamp','time'),oii=col('sum_open_interest','open_interest'),ovi=col('sum_open_interest_value','open_interest_value'),tri=col('sum_taker_long_short_vol_ratio','taker_long_short_ratio');if(ti<0||oii<0)throw new Error(`metrics CSV: required columns missing (${head.join(',')})`);const out:ArchiveMetricPoint[]=[];for(const line of lines.slice(1)){const c=line.split(','),timestamp=ts(c[ti]?.trim()??''),oi=Number(c[oii]);if(!Number.isFinite(timestamp)||!Number.isFinite(oi))continue;const ov=Number(c[ovi]),r=Number(c[tri]);out.push({timestamp,oi,oiValue:ovi>=0&&Number.isFinite(ov)?ov:null,takerBuyRatio:tri>=0&&Number.isFinite(r)&&r>=0?r/(1+r):null})}return out.sort((a,b)=>a.timestamp-b.timestamp)}
export function planMetricDays(fromMs:number,untilMs:number):string[]{const out:string[]=[];let t=Math.floor(fromMs/DAY)*DAY;for(;t<untilMs;t+=DAY){const d=new Date(t);out.push(`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`)}return out}
const missing=new Set<string>();async function loadDay(sym:string,day:string,o:ArchiveMetricOptions):Promise<ArchiveMetricPoint[]>{const dir=o.cacheDir??'.cache/binance',file=join(dir,`${sym}-metrics-${day}.json`);if(existsSync(file))try{return JSON.parse(readFileSync(file,'utf8'))as ArchiveMetricPoint[]}catch{}const key=`${sym}|${day}`;if(missing.has(key))return[];const f=o.fetchImpl??fetch,url=`${BASE}/${sym}/${sym}-metrics-${day}.zip`;for(let a=0;a<3;a++){try{const r=await f(url);if(r.status===404){missing.add(key);return[]}if(!r.ok){if(a<2){await new Promise(x=>setTimeout(x,300*(a+1)));continue}console.error(`[archiveMetrics] skip ${sym}-${day}: ${r.status}`);return[]}const p=parseMetricsCsv(unzipCsv(Buffer.from(await r.arrayBuffer())));mkdirSync(dir,{recursive:true});writeFileSync(file,JSON.stringify(p));return p}catch(e){if(a===2){console.error(`[archiveMetrics] skip ${sym}-${day}: ${String(e)}`);return[]}await new Promise(x=>setTimeout(x,300*(a+1)))}}return[]}
export async function fetchArchiveMetrics(symbol:string,fromMs:number,untilMs:number,o:ArchiveMetricOptions={}):Promise<ArchiveMetricPoint[]>{const sym=archiveSymbol(symbol),days=planMetricDays(fromMs,untilMs),parts:ArchiveMetricPoint[][]=[],p=Math.max(1,o.parallel??8);for(let i=0;i<days.length;i+=p)parts.push(...await Promise.all(days.slice(i,i+p).map(d=>loadDay(sym,d,o))));const by=new Map<number,ArchiveMetricPoint>();for(const x of parts.flat())if(x.timestamp>=fromMs&&x.timestamp<untilMs)by.set(x.timestamp,x);return[...by.values()].sort((a,b)=>a.timestamp-b.timestamp)}
export function alignArchiveMetrics(points:ArchiveMetricPoint[],candles:Candle[],maxAgeMs=2*ARCHIVE_METRICS_INTERVAL_MS):{oi:Array<number|null>;takerBuyRatio:Array<number|null>;covered:number}{const p=[...points].sort((a,b)=>a.timestamp-b.timestamp),oi:Array<number|null>=[],takerBuyRatio:Array<number|null>=[];let j=0,last:ArchiveMetricPoint|null=null,covered=0;for(const c of candles){while(j<p.length&&p[j]!.timestamp<=c.timestamp)last=p[j++]!;const ok=last!=null&&c.timestamp-last.timestamp<=maxAgeMs;oi.push(ok?last!.oi:null);takerBuyRatio.push(ok?last!.takerBuyRatio:null);if(ok)covered++}return{oi,takerBuyRatio,covered}}
